### ISSUE TITLE
provide prebuilt binaries

### ISSUE THREAD

**Issue by vilterp** [RelationalAI/rai-cli#33]
To simplify installation for users, we should build binaries for each OS for each release, and upload them here.

Perhaps this could be automated somehow with a GH action?

cc @NRHelmi

**Comment by cpetitpas** [comment]
Testing https://github.com/RelationalAI/rai-cli/releases/download/v0.1.2-alpha/rai-v0.1.2-alpha-linux-amd64.tar.gz reveals that the binary seems to work fine. No issues noted.
Thanks @NRHelmi !

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6814](https://relationalai.atlassian.net/browse/RAI-6814).

_This link is only accessible to employees of RelationalAI._
