### ISSUE TITLE
segfault if --profile names a non existent stanza, should issue error message

### ISSUE THREAD

**Issue by bradlo** [RelationalAI/rai-cli#8]

**Comment by bradlo** [comment]
there was an error in the detection of a missing stanza in the golang SDK.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5111](https://relationalai.atlassian.net/browse/RAI-5111).

_This link is only accessible to employees of RelationalAI._
